tag_prefix = "v"

pre_package_bump_hooks = [
    "cargo set-version -p {{package}} {{version}}"
]

[packages]
arrpc = { path = "." }
arrpc-core = { path = "arrpc-core" }
arrpc-derive = { path = "arrpc-derive" }
arrpc-contract = { path = "arrpc-contract" }

