[package]
name = "arrpc-derive"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.69"
quote = "1.0.33"
syn = { version = "2.0.39", features = ["full"] }
convert_case = "0.6.0"


[lib]
proc-macro = true
